# Vectorization
<hr>

In [1]:
import numpy as np
import time
import random

In [2]:
a = np.zeros(4)
print(f"np.zeros(4) :  a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4, ))
print(f"np.zeros(4, ) :  a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4) :  a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [0. 0. 0. 0.], a.shape = (4,), a data type = float64
np.zeros(4, ) :  a = [0. 0. 0. 0.], a.shape = (4,), a data type = float64
np.random.random_sample(4) :  a = [0.95404304 0.13744436 0.63223353 0.39737647], a.shape = (4,), a data type = float64


In [3]:
a = np.arange(4.)
print(f"np.arange(4) :  a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4) :  a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

np.arange(4) :  a = [0. 1. 2. 3.], a.shape = (4,), a data type = float64
np.random.rand(4) :  a = [0.81701981 0.93990346 0.12458811 0.38960105], a.shape = (4,), a data type = float64


## Operation on Vectors
<hr>

In [4]:
a = np.arange(10)
print(a)

# Accessing element
print(f"a[2] = {a[2]}, a[2].shape = {a[2].shape}")

print(f"a[-1] = {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print(f"Error: {e}")


[0 1 2 3 4 5 6 7 8 9]
a[2] = 2, a[2].shape = ()
a[-1] = 9
Error: index 10 is out of bounds for axis 0 with size 10


In [5]:
a = np.array([1, 2, 3, 4])
print(a) 

b = -a
print(b)

b = np.sum(a)
print(b)

b = np.mean(a)
print(b)

b = a ** 2
print(b)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])

print(a + b)

print(a - b)

[0 0 6 8]
[2 4 0 0]


## Vector Dot Product
<hr>

In [7]:
def dot(a, b):
    res = 0
    for i in range(len(a)):
        res += a[i] * b[i]

    return res

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 3, 4, 5])

print(f"dot(a, b) = {dot(a, b)}")
print(f"np.dot(a, b) = {np.dot(a, b)}")

dot(a, b) = 39
np.dot(a, b) = 39


### Comparing speed
<hr>

In [9]:
np.random.seed(0)
a = np.random.rand(100000000)
b = np.random.rand(100000000)

start = time.time()     # time.time() returns the current time in seconds since the epoch
dot(a, b)
end = time.time()

print(f"Time taken by dot(a, b) = {end - start}")

start = time.time()
np.dot(a, b)
end = time.time()

print(f"Time taken by np.dot(a, b) = {end - start}")

KeyboardInterrupt: 

In [10]:
def compare_speed():
    np.random.seed(0)
    n = random.randint(1000000, 5000000)

    a = np.random.rand(n)
    b = np.random.rand(n)

    start = time.time()
    dot(a, b)
    end = time.time()
    dot_time = start - end

    start = time.time()
    np.dot(a, b)
    end = time.time()
    np_dot_time = start - end

    del a
    del b

    return dot_time, np_dot_time

res_percent = 0
for i in range(100):
    dot_time, np_dot_time = compare_speed()
    percent = (dot_time - np_dot_time) / np_dot_time * 100
    res_percent += percent

print(f"Average percent difference = {res_percent / 1000}")

Average percent difference = 2727.3658020129124
